version: 2
updates:
  # 1. Surveille les dépendances Python (ton setup.py / pyproject.toml)
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"

  # 2. Surveille les mises à jour de tes robots GitHub Actions (tests, docs...)
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
